server:
  port: 8999

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:nacos-cloud.hongqy1024.cn}:${NACOS_PORT:8848}
        group: @nacos.group@
        namespace: @nacos.namespace@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        group: @nacos.group@
        namespace: @nacos.namespace@
  config:
    import:
      - nacos:application-@profiles.active@.yaml
      - nacos:${spring.application.name}-@profiles.active@.yaml