server:
  port: 8777

spring:
  application:
    name: @artifactId@

  config:
    import:
      - classpath:nacos_config.yml
      - nacos:dubbo.yml
      - nacos:@profiles.active@.yaml
      - nacos:redis.yaml