logging:
  config: classpath:logback.xml
server:
  port: 8002

spring:
  profiles:
    active: dev
  application:
    name: communication-service
  config:
    import:
      - classpath:nacos_config.yml
      - nacos:@profiles.active@.yaml
      - nacos:redis.yaml

