spring:
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        group: DEFAULT_GROUP
        namespace: ${NACOS_NAMESPACE:9cd8de3b-030a-49f1-9256-f04de35cdb9e}
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        group: DEFAULT_GROUP
        namespace: ${NACOS_NAMESPACE:6ff9c59b-f5a4-4d65-a4f3-2d32eb0fa70d}