def registry = "registry.cn-shenzhen.aliyuncs.com"
def image_name = "${registry}/hqy-parent-all/collector-service:1.0"
def jnlp_image = "registry.cn-shenzhen.aliyuncs.com/hqy-parent-all/jnlp-slave:latest"
def podman_image = "registry.cn-shenzhen.aliyuncs.com/hqy-parent-all/podman:latest"

def aliyun_hub = "aliyun-hub"

def base_dir = "/home/jenkins/agent/workspace/common-collector-service"
def service_jar = "common-collector-service.jar"

podTemplate(
    label: 'jenkins-agent',
    cloud: 'kubernetes',
    containers: [
      containerTemplate(name: 'jnlp',
                        image: "${jnlp_image}",
                        alwaysPullImage: false,
                        privileged: true,
                        ttyEnabled: true),

      containerTemplate(name: 'podman',
                        image: "${podman_image}",
                        alwaysPullImage: false,
                        privileged: true,
                        ttyEnabled: true)
    ],
    volumes: [
        hostPathVolume(mountPath: '/var/lib/containers', hostPath: '/var/lib/containers'),
        hostPathVolume(mountPath: '/usr/local/apache-maven-3.8.6/repo', hostPath: '/usr/local/apache-maven-3.8.6/repo')
    ]) {

    node('jenkins-agent'){
         stage('Git Clone') {
            dir("${base_dir}") {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/test']],
                    userRemoteConfigs: [[credentialsId: "", url: "https://github.com/nauyiq/hqy-parent-all.git"]],
                    extensions: [
                    [$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true]
                    ]
                ])
            }

         }

         stage('Maven Build') {
            dir("${base_dir}") {
                sh """
                    cd hqy-common-modules/hqy-common-collector-impl
                    mvn clean compile install -Dmaven.test.skip=true
                   """
            }
         }

        stage('Build Image') {
            container('podman') {
                stage('Package Image') {
                     withCredentials([usernamePassword(credentialsId: "${aliyun_hub}", passwordVariable: 'password', usernameVariable: 'username')]) {
                           sh """
                              cd ${base_dir}/hqy-common-modules/hqy-common-collector-impl/deploy
                              cp -rf ../target/lib .
                              cp -rf ../target/${service_jar} .
                              podman build -t ${image_name} .
                              podman login -u ${username} -p '${password}' ${registry}
                              podman push ${image_name}
                              """
                     }
                }
            }
        }
    }
}