server:
  port: 9527

spring:
  application:
    name: @artifactId@

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  config:
    import:
      - classpath:nacos_config.yml
      - classpath:dubbo.yml
      - nacos:@profiles.active@.yaml
      - nacos:redis.yaml

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      discovery:
        locator:
          enabled: true
    sentinel:
      datasource:
        ds:
          nacos:
            username: ${NACOS_USERNAME:nacos}
            password: ${NACOS_PASSWORD:nacos}
            serverAddr: ${NACOS_SERVER:127.0.0.1:8848}
            namespace: ${NACOS_NAMESPACE:6ff9c59b-f5a4-4d65-a4f3-2d32eb0fa70d}
            groupId: ${NACOS_GROUP:DEFAULT_GROUP}
            dataId: gateway-sentinel-flow
            data-type: json
            ruleType: flow

# 动态路由配置
gateway:
  dynamicRoute:
    dataId: gateway-routing.json
    group: ${NACOS_GROUP:DEFAULT_GROUP}
    enabled: true
    type: nacos

# 业务uris白名单配置
hqy4cloud:
  auth:
    white:
      uris: /blog/**

