// 镜像仓库地址
def registry = "registry.cn-shenzhen.aliyuncs.com"
// 命名空间
def namespace = "hqy-parent-all"
// 镜像仓库项目
def project = "collector-service"
//镜像版本号
def image_version="1.0"
// 镜像完整名称
def image_name = "${registry}/${namespace}/${project}:${image_version}"
// git仓库地址
def git_address = "https://github.com/nauyiq/hqy-parent-all.git"
// 分支
def branch = "*/test"
// jenkins aliyun认证
def aliyunhub_auth = "6c5aab53-0985-4ffc-bae7-0908c0b18961"
// K8s认证
def k8s_auth = "kubeconfig"
// aliyun仓库secret_name
def aliyun_registry_secret = "aliyun-pull-secret"


podTemplate(
    label: 'jenkins-agent',
    cloud: 'kubernetes',
    containers: [
       //containerTemplate(name: 'jnlp', image: "docker.io/jenkins/inbound-agent:latest"),
        containerTemplate(name: 'jnlp', image: "docker.io/jenkins/jnlp-slave:latest"),
       containerTemplate(name: 'docker', image: 'docker.io/docker:latest', ttyEnabled: true, command: 'cat')
    ],
    volumes: [
        hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')
    ]){
    node('jenkins-agent'){
        stage('拉取代码') { // for display purposes
            checkout([$class: 'GitSCM',branches: [[name: '*/master']], userRemoteConfigs: [[credentialsId: "", url: "${git_address}"]]])
        }
        stage('代码编译') {
        //    sh "mvn clean package -Dmaven.test.skip=true"
            sh "ls"
        }
        stage('构建镜像') {
            container('docker') {
                stage('打包镜像') {
                   withCredentials([usernamePassword(credentialsId: "${aliyunhub_auth}", passwordVariable: 'password', usernameVariable: 'username')]) {
                   sh """
                      docker build -t ${image_name} .
                      docker login -u ${username} -p '${password}' ${registry}
                      docker push ${image_name}
                   """
                    }
                }
            }
        }
        stage('部署到K8s'){
            sh """
                sed -i 's#\$IMAGE_NAME#${image_name}#' deployment.yaml
                sed -i 's#\$SECRET_NAME#${aliyun_registry_secret}#' deployment.yaml
                sed -i 's#\$NODE_PORT#${nodePort}#' deployment.yaml

            """
             kubernetesDeploy configs: 'deployment.yaml', kubeconfigId: "82eb8e6c-da8f-44cd-837b-2acb02d328fb"
        }
    }
}